apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  replicas: 1 # using the value 10 will create 10 pods wich one wiht a container
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "wesleywillians/hello-go:v5.4"

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000 # port of container
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 10


          envFrom:
          - configMapRef:
              name: goserver-env
          - secretRef:
              name: goserver-secret
          
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true
      
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"
          
          